openapi: 3.1.0
info:
  title: Camphand API
  description: |
    ## Camphand Application API

    This API provides endpoints for the Camphand application.

    ### Features:
    * **Messages**: Get hello messages from the API
    * **Health**: Monitor API health status

    ### Authentication:
    Currently no authentication is required.
  version: 1.0.0
  contact:
    name: Camphand Team
    email: contact@camphand.com
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:8000
    description: Development server

tags:
  - name: Messages
    description: Operations with messages and greetings
  - name: Health
    description: Health check and monitoring endpoints

paths:
  /api:
    get:
      summary: Get Hello Message
      description: Returns a simple hello message from the API
      tags:
        - Messages
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello API"
                required:
                  - message

  /health:
    get:
      summary: Health Check
      description: Check if the API is running and healthy
      tags:
        - Health
      responses:
        "200":
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  service:
                    type: string
                    example: "Camphand API"
                required:
                  - status
                  - service

components:
  schemas:
    MessageResponse:
      type: object
      properties:
        message:
          type: string
          example: "Hello API"
      required:
        - message

    HealthResponse:
      type: object
      properties:
        status:
          type: string
          example: "healthy"
        service:
          type: string
          example: "Camphand API"
      required:
        - status
        - service
